project:
  type: website

# website
website:
  # basics
  title: "dkdc.dev"
  site-url: https://dkdc.dev
  description: "Cody's website"
  favicon: logo.png

  # options
  reader-mode: false
  twitter-card: true
  back-to-top-navigation: true
  repo-url: https://github.com/lostmygithubaccount/dkdc.dev

  # nav
  navbar:
    logo: logo.png
    fontcolor: fuchsia
    left:
      - about.qmd
    right:
      - posts.qmd
      - sidebar:dashboards
  sidebar:
    - id: ""
    - id: dashboards
      title: "some projects"
      style: "docked"
      collapse-level: 2
      contents:
        - text: ibis-analytics
          href: https://ibis-project.github.io/ibis-analytics
        - text: ibis-bench
          href: https://lostmygithubaccount.github.io/ibis-bench
        - text: better-pypi-stats
          href: https://connect.posit.cloud/lostmygithubaccount/content/019180af-9e47-14bd-0955-38e6d98a5f98

  # footer
  page-footer:
    border: false
    center: "Cody's website"
    right:
      - icon: github
        href: https://github.com/lostmygithubaccount
      - icon: linkedin
        href: https://linkedin.com/in/codydkdc
      - icon: twitter
        href: https://dkdc.dev/posts
      - icon: rss
        href: https://dkdc.dev/posts.xml

# theme
format:
  html:
    theme: vapor
    fontcolor: fuchsia
    linkcolor: fuchsia
    css: styles.css
    toc: true

# resources
resources:
  - CNAME
