project:
  type: website

# website
website:
  # basics
  title: "dkdc.dev"
  site-url: https://dkdc.dev
  description: "Cody's website"
  favicon: logo.png

  # options
  reader-mode: false
  twitter-card: true
  back-to-top-navigation: true
  repo-url: https://github.com/lostmygithubaccount/dkdc.dev
  # repo-actions: [edit, issue]


  # nav
  navbar:
    logo: logo.png
    fontcolor: fuchsia
    left:
      - posts.qmd
    right:
      - sidebar:links
      - sidebar:dashboards
      - sidebar:slides
      - about.qmd
      - contact.qmd
      - ai.qmd
  sidebar:
    - id: ""
    - id: links
      title: "links"
      style: "docked"
      collapse-level: 2
      contents:
        - text: dkdc.dev
          href: https://dkdc.dev
        - text: Ibis
          href: https://ibis-project.org
        - text: GitHub
          href: https://github.com
        - text: GitHub - dkdc.dev
          href: https://github.com/lostmygithubaccount/lostmygithubaccount.github.io
        - text: GitHub - Ibis
          href: https://github.com/ibis-project/ibis
        - text: Azure
          href: https://portal.azure.com
        - text: Azure OpenAI
          href: https://oai.azure.com/portal
        - text: OpenAI
          href: https://platform.openai.com
        - text: Streamlit
          href: https://share.streamlit.io
        - text: MotherDuck
          href: https://app.motherduck.com
        - text: "localhost:8000 (mkdocs)"
          href: http://localhost:8000
        - text: "localhost:8501 (streamlit)"
          href: http://localhost:8501
        - text: "localhost:3000 (dagster)"
          href: http://localhost:3000
    - id: dashboards
      title: "dashboards"
      style: "docked"
      collapse-level: 2
      contents: "*-metrics.qmd"
    - id: slides
      title: "slides"
      style: "docked"
      collapse-level: 2
      contents: "*-slides.qmd"

  # footer
  page-footer:
    border: false
    center: "Cody's website"
    right:
      - icon: linkedin
        href: https://linkedin.com/in/codydkdc
      - icon: github
        href: https://github.com/lostmygithubaccount
      - icon: rss
        href: https://dkdc.dev/posts.xml

# theme
format:
  html:
    theme: vapor
    fontcolor: fuchsia
    linkcolor: fuchsia
    css: styles.css
    toc: true

# resources
resources:
  - CNAME
