project:
  type: website

# website
website:
  # basics
  title: "dkdc.dev"
  site-url: https://dkdc.dev
  description: "Cody's website"
  favicon: logo.png

  # options
  reader-mode: false
  twitter-card: true
  back-to-top-navigation: true
  repo-url: https://github.com/lostmygithubaccount/dkdc.dev
  search: false

  # nav
  navbar:
    logo: logo.png
    #left:
    #   - about.qmd
    #right:
      # - posts.qmd

  # footer
  page-footer:
    border: false
    center: "Cody's website"
    right:
      - icon: brilliance
        href: https://dkdc.dev/about
      - icon: github
        href: https://github.com/lostmygithubaccount
      - icon: linkedin
        href: https://linkedin.com/in/codydkdc
      # - icon: body-text
      #   href: https://dkdc.dev/posts

# theme
format:
  html:
    theme: vapor
    fontcolor: fuchsia
    linkcolor: fuchsia
    css: styles.css
    toc: true

# resources
resources:
  - CNAME
