project:
  type: website

# website
website:
  # basics
  title: "dkdc.dev"
  site-url: https://dkdc.dev
  description: "Cody's website"
  favicon: logo.png

  # options
  reader-mode: false
  twitter-card: true
  back-to-top-navigation: true
  repo-url: https://github.com/lostmygithubaccount/dkdc.dev
  # repo-actions: [edit, issue]


  # nav
  navbar:
    logo: logo.png
    fontcolor: fuchsia
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/lostmygithubaccount/dkdc.dev
          - text: Discussions
            url: https://github.com/lostmygithubaccount/dkdc.dev/discussions/categories/comments
    left:
      - posts.qmd
    right:
      - sidebar:links
      - sidebar:dashboards
      - sidebar:slides
      - about.qmd
      - contact.qmd
      - ai.qmd
  sidebar:
    - id: ""
    - id: links
      title: "links"
      style: "docked"
      collapse-level: 2
      contents:
        - text: dkdc.dev
          href: https://dkdc.dev
        - text: reader
          href: https://read.readwise.io/feed/unseen
        - text: email
          href: https://mail.google.com/mail
        - text: calendar
          href: https://calendar.google.com/calendar
        - text: drive
          href: https://drive.google.com/drive/my-drive
        - text: ibis
          href: https://ibis-project.org
        - text: github
          href: https://github.com
        - text: github - dkdc.dev
          href: https://github.com/lostmygithubaccount/dkdc.dev
        - text: github - ibis
          href: https://github.com/ibis-project/ibis
        - text: azure
          href: https://portal.azure.com
        - text: azure openai
          href: https://oai.azure.com/portal
        - text: openai
          href: https://platform.openai.com
        - text: gcp
          href: https://console.cloud.google.com
        - text: streamlit
          href: https://share.streamlit.io
        - text: motherduck
          href: https://app.motherduck.com
        - text: keyboard
          href: https://configure.zsa.io/moonlander
        - text: "localhost:8501 (streamlit)"
          href: http://localhost:8501
        - text: "localhost:3000 (dagster)"
          href: http://localhost:3000
    - id: dashboards
      title: "dashboards"
      style: "docked"
      collapse-level: 2
      contents:
        - text: ibis-analytics
          href: https://ibis-analytics.streamlit.app
        - text: pypi-analytics
          href: https://pypi-analytics.streamlit.app
    - id: slides
      title: "slides"
      style: "docked"
      collapse-level: 2
      contents: "*-slides.qmd"

  # footer
  page-footer:
    border: false
    center: "Cody's website"
    right:
      - icon: twitter
        href: https://dkdc.dev/posts
      - icon: github
        href: https://github.com/lostmygithubaccount
      - icon: linkedin
        href: https://linkedin.com/in/codydkdc
      - icon: rss
        href: https://dkdc.dev/posts.xml

# theme
format:
  html:
    theme: vapor
    fontcolor: fuchsia
    linkcolor: fuchsia
    css: styles.css
    toc: true

# resources
resources:
  - CNAME
