---
title: "about"
---

## me

Hello! My name is Cody (he/him). I'm passionate about progress via technology.

Currently for hire! Probably. Feel free to [reach out](#contact).

Previously a Senior Technical Product Manager at [Voltron Data](https://voltrondata.com) focusing on data interfaces and awesome OSS like [Ibis](https://ibis-project.org). Previously a Product Manager at [dbt Labs](https://getdbt.com) focusing on OSS (Python models) and Cloud (internal platform). Previously a Product Manager II at [Microsoft (AI Platform | Azure ML)](https://azure.microsoft.com/products/machine-learning) focusing on data, MLOps, and v2 developer experiences.

See my [GitHub](https://github.com/lostmygithubaccount) and/or [LinkedIn](https://www.linkedin.com/in/codydkdc) for more details on my experience.

I care about:

- OSS & scale
- beautiful design
- elegant engineering

## website

**This is my personal website. My views are separate from my (potential) employer's.**

The purpose of this website is to practice writing, coding, and documenting projects.

## contact

:::{.callout-warning}
No soliciting! Please...
:::

### GitHub

You can tag on GitHub using [@lostmygithubaccount](https://github.com/lostmygithubaccount) to drastically improve the chance I see the notification and respond.

### personal

Reach out [via email](mailto:cody@dkdc.dev) (preferred) or LinkedIn.

