---
format:
  pdf:
    colorlinks: true
    include-in-header:
      text: '\pagenumbering{gobble}\hyphenpenalty=10000\exhyphenpenalty=10000'
    pdf-engine: xelatex
fontsize: 10pt
geometry:
  - top=20mm
  - left=15mm
  - heightrounded
---

# Cody Peterson (he/him) | [Email](mailto:cody@dkdc.dev) | [GitHub](https://github.com/lostmygithubaccount) | [LinkedIn](https://linkedin.com/in/codydkdc) | [Personal website](https://dkdc.dev)

## Work experience

**Voltron Data** (Ibis project)

*Senior Technical Product Manager* | April 2024 - September 2024 | remote

- Led marketing and developer advocacy for Ibis resulting in GitHub stars doubling, PyPI downloads tripling, and documentation visits quintupling year-over-year
- Built composable data stacks for analytics, benchmarking, and more to achieve desired product outcomes
- Worked with executives and product leadership to re-align product direction for new stream processing and ML features across OSS and commercial offerings, enabling more efficient use of engineering resources

*Technical Product Manager* | May 2023 - April 2024 | remote

- Migrated the Ibis website to Quarto for better UX, easier contributions, and a proper blog
- Planned and executed a GenAI/LLM strategy for OSS and commercial offerings with Ibis Birdbrain
- Contributed features, bug fixes, and blog posts to the Ibis project, becoming a trusted committer to `ibis` and maintainer of several side projects in the GitHub organization

**dbt Labs** (dbt Core & dbt Cloud)

*Product Manager* | July 2022 - March 2023 | remote

- Launched Python models at company conference, enabling the first data science & ML use cases
- Assumed management of cloud platform team and led alignment of stakeholders on major roadmap adjustment to achieve better product outcomes and more efficient engineering execution

**Microsoft** (AI Platform, Azure ML)

*Product Manager II* | March 2020 - July 2022 | Bellevue, WA & remote

- Led development for v2 product features in the data & MLOps areas, resulting in higher usability score
- Improved strategy for examples and documentation in collaboration with key stakeholders, resulting in positive qualitative feedback from users and a significant increase in contributions
- Increased satisfaction for strategic cloud customer as primary point of engagement for the product team

*Product Manager* | July 2018 - February 2020 | Bellevue, WA

- Filled gap in Azure MLOps marketing story by leading cross-disciplinary team of developers and data scientists to launch a data drift monitoring feature ahead of major cloud competitors
- Led development of open-source contribution to Dask to run on Azure ML infrastructure
- Deprecated legacy internal products, managing engineering and working with customers on migration

## Education

**Rice University** | 2014 - 2018 | Houston, TX

*B.S. Electrical Engineering with Data Science specialization*, 3.5/4.0 GPA

## Skills & technologies

**Advanced:** Python (data, ML, & "AI" tools), GitHub, data platforms, cloud services (Azure/GCP)

**Intermediate:** Go, Rust, git, Docker, SQL, UNIX/Linux systems, Raspberry Pis

**Once upon a time:** C, Perl, MATLAB, JavaScript, Verilog, FPGAs, CAD, 3D printing, Figma, PowerBI

{{< pagebreak >}}

## Additional work experience

**Convergent Engineering** | (New product R&D)

*Consultant* | Summer 2017 | Newberry, FL

- Delivered prototype system for alerting nurses to non-critical alarms in patient rooms, including live testing with IRB-approved study at the UF Shands Hospital in Gainesville, FL

**Texas Instruments** (System on a Chip [SoC] Design Verification)

*Design Engineering Intern* | Summer 2016 | Dallas, TX

- Reduced average SoC simulation runtime by six percent through discovery of optimal simulation configuration via benchmarking tool designed and implemented with engineering mentor
- Decreased time to debug SoC simulations by partnering with three engineers to build tools for efficient printf simulation and a user-friendly web interface to determine signal routing through chip components

**Convergent Engineering** (Various projects)

*Engineering Intern* | Summer 2015 | Newberry, FL

- Automated data collection and analysis from proprietary e-pill devices with a CLI over Bluetooth
- ECG data collection and signal analysis from multiple hardware platforms
