---
title: "beware the metagame"
author: "Amjad Masad"
date: "2023-09-11"
categories: 
    - meta
---

[https://amasad.me/meta](https://amasad.me/meta)

> I've first noticed this problem in the startup world where you see famous people that sell books, talk at conferences, and tweet advice to founders, but when you take a closer look, they've never done much founding themselves. They're like the "entrepreneurship" professor that never built a business. They're experts in the metagame -- they're polished speakers, engaging writers, and thought-leadering tweeters. The problem, though, is that they're not judged by customers, the market, or nature, instead they're judged by their peers. I call them metapreneurs.
> 
> This is an instance of what Nassim Taleb calls "The Expert Problem" -- when other experts and meta-experts judge experts. Eventually the lack of contact with reality will corrupt the field. In the sciences, that lead to the replication crisis and the absurdities of the humanities.
> 
> If you find yourself going to a lot of conferences, opining too much on the latest fad in your field, and talking more about doing the thing than doing the job itself, then you, my friend, are getting sucked into the metagame.
